### ISSUE TITLE
ゲームプログラムの基本設計（Architecture Design）を完成する

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#11]
まだ仕様書はないんですが、これを完成すれば、他の経験が少ない人も実装に移りやすくなるので、現在一番重要なタスクかと思います。アバウトでいいので基本設計（Architecture Design）を完成してほしいです。

**Comment by Onka10** [comment]
開発中止
discontinue development
