### ISSUE TITLE
2Dスクロールゲームのフレームワークを探す

### ISSUE THREAD

**Issue by lyn-teambeta** [JiaChen-Zeng/PRNL-Alpha01#14]
https://moon-bear.com/2020/03/31/unity-assets-2020/

**Comment by lyn-teambeta** [comment]
2D Flexible Platformer Controller が便利そうでした

**Comment by JiaChen-Zeng** [comment]
そのフレームワークが使えないか @avinash4400  にチェックしてもらうようにお願いしました

**Comment by JiaChen-Zeng** [comment]
@avinash4400 さんの意見が来ました。2D Flexible Platformer Controller が複雑すぎたので、Unity の内蔵アセットを使うことに決めました。
