### ISSUE TITLE
弾幕のデザインについて調べて参考資料をここにまとめる

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#15]
どういう弾幕があるかを知っておきます。

**Comment by lyn-teambeta** [comment]
【Unity C#】弾幕のように全方向へ発射するしくみ
https://futabazemi.net/notes/unity-quaternion_rotation/

Re:ゼロから始める弾幕アルゴリズム　～　Unityで作る弾幕STG
https://noranuk0.hatenablog.com/entry/2016/10/29/235004

**Comment by JiaChen-Zeng** [comment]
すみません！実装の話じゃないです。他のゲームがどういう弾幕のパターンとかがあるかが知りたいですね。

**Comment by lyn-teambeta** [comment]
では、2つ目のサイトでいくつか紹介されてます。

**Comment by JiaChen-Zeng** [comment]
ざっと読んでみたんですが、比較的に情報が少ないですね。なるべく網羅してほしいんです。

**Comment by lyn-teambeta** [comment]
了解です。

**Comment by lyn-teambeta** [comment]
https://www.youtube.com/watch?v=xbQ9e0zYuj4
これとかどうでしょうか？

**Comment by JiaChen-Zeng** [comment]
このような感じの資料で間違いないです。他にもあると思うので、できれば一回のコメントで全部まとめてほしいですね。特徴とパターンも少し分類してもらえば助かります。

**Comment by lyn-teambeta** [comment]
https://noranuk0.hatenablog.com/entry/2016/10/29/235004

https://www.youtube.com/watch?v=xbQ9e0zYuj4

https://www.youtube.com/watch?v=H7gMlHrPU3w

https://www.youtube.com/watch?v=8LxIeRE0slc

https://www.youtube.com/watch?v=6ZlkZL-ixGc

https://www.youtube.com/watch?v=GDs3QEbV_l0

**Comment by JiaChen-Zeng** [comment]
本当にまとめしかしていなかったようですが、これはこれでこのissueは完成とします。
