### ISSUE TITLE
アートコンセプトを確定させる

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#17]
このゲームのコンセプトに合いそうで、且つわたしたちで作れそうなアートコンセプトを探します。まずは方向性が違うものをいくつか集めてから決めましょう。以下でサイトから探しやすいと思うので、参考にしてください。

- https://www.gameuidatabase.com/
- https://www.pinterest.jp/lifuericalin/game-ui/
- https://www.pinterest.jp/oldpanda0661/game-ui/

**Comment by lyn-teambeta** [comment]
https://drive.google.com/drive/folders/1zXooz7zMD4a2mMF-i9Xq84UquqnHL4Pl?usp=sharing

ピンとくるものがあまりなく、数は少ないですが・・・。
どなたでも編集出来るようになっているはずなので、好きに使ってください。

**Comment by lyn-teambeta** [comment]
![5d5c1c98-235c-466c-b72c-dbe8ed18f6c9_base_resized](https://user-images.githubusercontent.com/86309684/147186469-92bdeb45-babd-4ae4-9c7b-3715bd609af1.jpg)
![1003_captainamerica](https://user-images.githubusercontent.com/86309684/147186476-4b58fdc1-6b40-4710-ac4f-de7aa546ff7c.jpg)
![20726313_p0_master1200](https://user-images.githubusercontent.com/86309684/147186479-59c1c24f-7b93-4dc2-84d5-efc1c5888e25.jpg)
![38005478_p0_master1200](https://user-images.githubusercontent.com/86309684/147186484-223c7b00-3435-43c8-bfda-2c43fdaff07d.jpg)
![76380868_p0_master1200](https://user-images.githubusercontent.com/86309684/147186491-c859d1e6-5bc9-4b3f-bb15-744cdda9ed35.jpg)
![9145112920094](https://user-images.githubusercontent.com/86309684/147186497-2dddda41-12f6-4090-a908-6c0d85e6257f.jpg)
![cardimage](https://user-images.githubusercontent.com/86309684/147186501-87ade38c-128b-4ebf-9b36-46379ee66780.png)
![EIfYd40VAAAzk-U](https://user-images.githubusercontent.com/86309684/147186502-f7574034-4c42-48ce-89e0-95125f21af1a.jpg)
![rLhsOhC](https://user-images.githubusercontent.com/86309684/147186506-66e970d0-3295-45f6-8320-f089c00e5b3e.png)

**Comment by lyn-teambeta** [comment]
https://www.whiteorder.net/shield-kaisetsu/

**Comment by JiaChen-Zeng** [comment]
たくさん調べてもらっていながら恐縮なんですが、盾のアートコンセプトではなく、ゲーム全体の雰囲気が掴められるアートコンセプトがほしいです。それに画像だけではなくどういう雰囲気なのかも文字で説明してもらえれば助かります。

**Comment by lyn-teambeta** [comment]
![painting-tower-of-babel-wallpaper-preview](https://user-images.githubusercontent.com/86309684/147188477-209d2d4f-dc6f-4301-800e-a39851fd6ff2.jpg)
![july01_a04](https://user-images.githubusercontent.com/86309684/147188489-bd0b299a-d2c5-4a4f-bf23-0279e94411b0.png)
![icon_trt_result_16a](https://user-images.githubusercontent.com/86309684/147188499-8e31a7fa-7192-4065-9057-1659cb799d5a.png)
山or塔を登っていくイメージ

**Comment by lyn-teambeta** [comment]
![94946883_p0_master1200](https://user-images.githubusercontent.com/86309684/147188551-565cc84a-1a95-4a87-990d-8add476b2992.jpg)
![9145112920094](https://user-images.githubusercontent.com/86309684/147188555-606d747b-f616-4c9a-81dc-b6dac1e6a2a1.jpg)
![bv076](https://user-images.githubusercontent.com/86309684/147188559-ab73579d-cd12-496c-b4e8-cf9c29b28762.png)

盾を持ったかわいいキャラクターが主人公のイメージ

**Comment by lyn-teambeta** [comment]
![images](https://user-images.githubusercontent.com/86309684/147188640-ff0dcf4f-b270-47ff-90ea-befeb2f1968f.png)
![100x100-75](https://user-images.githubusercontent.com/86309684/147188641-12f3ed3c-f785-4ace-ad28-33fdb6116c6e.jpg)

たくさんのスライム？と戦うイメージ

**Comment by lyn-teambeta** [comment]
![sss107](https://user-images.githubusercontent.com/86309684/147188902-d2d19ace-b496-4bbf-a15b-46baf021532c.jpg)
何度も挑戦したが、失敗したイメージ

**Comment by lyn-teambeta** [comment]
![review_0531_katatemakuesuto_1-thumb-500x281-9809 (1)](https://user-images.githubusercontent.com/86309684/147191585-34130074-a9b9-4a41-9d49-3482a5809a8d.png)
![a0fcf843b17dd85d6bf23e5a0ad28270-800x450](https://user-images.githubusercontent.com/86309684/147191589-903d5160-c2f5-4a5f-ac5e-fa316414a4e2.jpg)

可愛らしいゲームイメージ

**Comment by JiaChen-Zeng** [comment]
時間もあまりないのでもう化物語っぽいアートコンセプトでいいかなって思えてきました。
