### ISSUE TITLE
主人公の見た目と動きを作る、またはアセットを探す

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#18]
仕様書のイメージ図に使える絵を探すときにアセットを見かけました。ゲームが最終的にこれを使うかどうか関係なく、まずイメージ図作りのために使いたいと思います。

https://assetstore.unity.com/packages/2d/characters/2d-simple-character-swordman-133259

**Comment by Onka10** [comment]
仮にアートを私達で用意する場合、このアセットの画像データに合わせてアートを用意する。という事で間違いないですか？

**Comment by JiaChen-Zeng** [comment]
> このアセットの画像データに合わせて

というのはどういう意味ですか？

**Comment by Onka10** [comment]
アセットのキャラクターのパーツ、つまり足や頭などを私達で新たにデザインして置き換えるという意味です

**Comment by JiaChen-Zeng** [comment]
それでやりやすかったらそうするほうがいいですね。ただわたし Unity でキャラとアニメーションを作ったことがないので確信が持てないというのがあります。Discord でチームメンバーにでも他のプロの方にでも聞いてみましょうか。わたしはぱっと見使いやすそうだと感じたので、これに合わせて絵を用意するのはいいと思います。

**Comment by Onka10** [comment]
> それでやりやすかったらそうするほうがいいですね。ただわたし Unity でキャラとアニメーションを作ったことがないので確信が持てないというのがあります。Discord でチームメンバーにでも他のプロの方にでも聞いてみましょうか。わたしはぱっと見使いやすそうだと感じたので、これに合わせて絵を用意するのはいいと思います。

詳しく見ていないので分かりませんが、https://assetstore.unity.com/packages/templates/systems/2d-flexible-platformer-controller-67414
このアセットをVickyさんは使用していたと思います。
私は以前、このアセットのプレイヤーキャラクターを差し替えて実装を行った事があるので絵を用意することは可能です。

**Comment by JiaChen-Zeng** [comment]
あ、実は前回はこのアセットは捨てるという話だったんです。柔軟ではないので一から作ったほうが早いということでした。

**Comment by Onka10** [comment]
そうなんですね、分かりました

**Comment by Onka10** [comment]
プレイヤー関連のアートについてまとめました。

プレイヤー必要素材

イラスト素材
・プレイヤー
・盾

モーション
・待機
・歩行
・ジャンプ
・盾ジャンプ
・盾攻撃
・落下
・後退

**Comment by Onka10** [comment]
主人公の見た目についてのイメージはありますか？
・仕様書のようなアイコンに近い抽象的な人間
・しっかりとデザインした人間

**Comment by Onka10** [comment]
![147119202-1e178c60-b7a1-45bd-86d0-ae5626a2c786](https://user-images.githubusercontent.com/87790609/147388274-16c634f5-fed9-4015-bcf5-403161beeba3.png)

キャラクターの見た目が決まりました

**Comment by Onka10** [comment]
![147119202-1e178c60-b7a1-45bd-86d0-ae5626a2c786](https://user-images.githubusercontent.com/87790609/147388311-30e0402a-7c36-4b93-8297-c522650c5999.png)
盾無し

**Comment by Onka10** [comment]
@JiaChen-Zeng 
このキャラクターはhttps://assetstore.unity.com/packages/templates/systems/2d-flexible-platformer-controller-67414
に同梱されていたものですよね？
無料のアセットなのでクレジットにアセットを載せて使わせて頂きましょう。

盾は恐らくwindowsのアイコンですよね？なので盾はキャラクターに合わせてデザインします。
盾は正の字が書かれたもの。という記述を見かけたような気がするのですが、私の気のせいだったでしょうか？
他にも盾のデザインに関しての要望があればお聞かせください

**Comment by JiaChen-Zeng** [comment]
そのアセットのキャラクターで間違いありません。クレジットはテキストファイルとしてプロジェクトに置いておきましょうか。

盾は Affinity で shield で検索したら出てきた著作権フリーの絵です。盾に正の字が書かれているのはいいと思います！前はライフポイントの話で言っていました。

**Comment by Onka10** [comment]
全然Windows関係ありませんでしたねw

キャラクターの絵柄に寄せて、正の字が書かれている盾のデザインしてみます

**Comment by JiaChen-Zeng** [comment]
この絵は自分も Windows に連想しましたね。たぶんコントロールパネルの中のアイコンこんな感じだった気がします

**Comment by Onka10** [comment]
盾アイデア
![shield](https://user-images.githubusercontent.com/87790609/147398406-493577c6-3e29-406e-93f5-f0bff0948928.png)
![shield2](https://user-images.githubusercontent.com/87790609/147398407-5cc7d2bd-6aa1-4c9e-a539-4d940b50c6ce.png)
![shield3](https://user-images.githubusercontent.com/87790609/147398408-3a06036a-3dc0-49ad-9598-ad50e9ee2a00.png)

**Comment by JiaChen-Zeng** [comment]
わたしは2番目がいいと思いました。

1. コンセプトはおもしろいと思います。でも見た目上きれいに見えないのが難点です。
2. 正がギリギリわかりそうでおしゃれですね。暗い色も比較的に目立つデザインで正義のコンセプトが出てるのでいいと思いました
3. これは一番わかりやすいですね。とはいえ、正義が正しすぎてゲームのコンセプトがわかりにくくなる可能性がある気がしました。

**Comment by Onka10** [comment]
![正義マン](https://user-images.githubusercontent.com/87790609/147399470-77312580-15f5-495b-bd64-80ef02d42a11.png)

**Comment by Onka10** [comment]
![shield](https://user-images.githubusercontent.com/87790609/147400052-d4c2e9f3-4f02-4b1f-bba5-e3a4ad597eef.png)
![seigiman](https://user-images.githubusercontent.com/87790609/147400054-51165f9d-4e0a-414c-a2d0-00a5efd51256.png)
完成しました

**Comment by Onka10** [comment]
デザインに問題が無ければUnityプロジェクトで画像のみ差し替えテストをお願いします
差し替えが上手くいった場合、私はアニメーションの作成を開始します。

**Comment by JiaChen-Zeng** [comment]
いいですね！もう少し影が足りない気はしますが、どう思いますか？

**Comment by Onka10** [comment]
はい。影は少し悩みました。
というのも、影を足しすぎると回転した時に影について違和感が生じる可能性があるからです

**Comment by JiaChen-Zeng** [comment]
なるほど、じゃあまずはこのままにしましょうか

**Comment by Onka10** [comment]
実際に動かしてみて、やはり影がもう少し欲しいと感じた場合は遠慮なく言ってください。
修正は可能です

**Comment by JiaChen-Zeng** [comment]
わかりました！

**Comment by Onka10** [comment]
![player](https://user-images.githubusercontent.com/87790609/147400241-e0aeb643-dde8-427a-9ed6-37156d791baf.png)
playerの画像

**Comment by JiaChen-Zeng** [comment]
あ、ファイルは直接プロジェクトの中にアップロードしたほうがいいかもしれませんね。

ちなみに絵のソースファイルもプロジェクトの中においても大丈夫かなと思います。これは Artifacts のフォルダーに置きますね。

**Comment by Onka10** [comment]
了解です

**Comment by Onka10** [comment]
![スクリーンショット (286)](https://user-images.githubusercontent.com/87790609/147671247-f2de41a7-541a-47a7-a84c-6281a85dccc7.png)

キャラと盾のプログラムが実装出来ていたので、スプライトをアタッチして頂ければと思います。
プログラムに最適な大きさが決まった場合、連絡を頂ければスプライトの大きさを確定し、アニメーションの制作に入ります

一応自分でもテストはしました。これは少しスプライトを大きくしています。そのままのサイズだと小さいかもしれません

**Comment by Onka10** [comment]
![shield](https://user-images.githubusercontent.com/87790609/147672055-5e3bfb5b-ac20-4e83-a427-30a987d2fdcc.png)
![player](https://user-images.githubusercontent.com/87790609/147672056-b82b5027-9d6e-4cfa-b75f-b2fe35518f78.png)
念の為もう一度完成品を貼っておきます

**Comment by JiaChen-Zeng** [comment]
今プルしたんですが何もなかったです。恐らくプッシュされてなかったですね。確認してみてください。

**Comment by Onka10** [comment]
すみません追加しました

**Comment by JiaChen-Zeng** [comment]
確認できました。絵はもうそちらでゲームに入れたけどその部分はアップロードしていないということですね。そちらでもう入れてるならそれを使えばいいとは思うんですけどね。

また、Artifacts は絵のソースファイルを置くところですね。書き出された完成品は直接 Assets に入れればいいですね。

今 Simple Character Controller は入れてないですよね。本番なら恐らくそれを入れてから見た目調整するかなと思いますが、今のところはそのまま絵を入れてみます。あとでこの部分は削除しますね。

**Comment by JiaChen-Zeng** [comment]
絵の外側に空いているところがあります。消しといてくださいね。

![image](https://user-images.githubusercontent.com/3676278/147723627-c54956c0-2bfb-44e2-9616-49981e8a0113.png)

**Comment by Onka10** [comment]
はい。
大きさに関しても問題ありませんか？複数の問題点を確認して修正したものをアップします

**Comment by JiaChen-Zeng** [comment]
言われてなきゃ忘れるところでした！今の画像の解像度は小さすぎたと思います。500px くらいは必要かなと思ってますね。それでエディター内で絵の大きさを調整すると思います

**Comment by JiaChen-Zeng** [comment]
絵の解像度についてまず調べておく必要があると思います。通常、解像度は 1x 2x 3x 4x 違うバージョンを 4 つ用意する必要があると聞いています。具体的なやり方はわたしはわからないです。

**Comment by Onka10** [comment]
解像度修正してプッシュしました

**Comment by JiaChen-Zeng** [comment]
確認できました。でも今度修正された絵は直接 Assets に入れてください。

**Comment by JiaChen-Zeng** [comment]
この解像度はそのまま大きくしたものですか？若干ぼやけて見えました。元々絵を描くときキャンバスが小さかったでしょうか？でしたら AI アップスケーリングで解像度を上げたほうがいいかもですね。

あとは解像度は普通 2 のべき乗倍だというところを Texture の設定を見て思い出しました。ゲームの絵の解像度についてはちゃんと調べておく必要があるかもしれないですね。調べたら参考資料をシェアしてください。

**Comment by Onka10** [comment]
盾のぼかしは癖で入れてます
キャラクターはもともとの絵を大きくしてるので、もしかすると書き直す必要があるかもしれません

**Comment by JiaChen-Zeng** [comment]
なるほど、キャラは AI アップスケーリングを使えばきれいに解像度を上げられると思うので問題はないかと思います

**Comment by Onka10** [comment]
![shield](https://user-images.githubusercontent.com/87790609/147752462-a47fa673-7f44-4a27-8ce5-a8a964326096.png)
盾の高解像度

**Comment by Onka10** [comment]
![seigiman](https://user-images.githubusercontent.com/87790609/147752738-f21c2b37-68f0-478f-85bf-d619da8047a9.png)
主人公の高解像度版ですこれはアセットの画像を引き伸ばしているので書き直しが必要そうですね

**Comment by JiaChen-Zeng** [comment]
AI アップスケーリングのサービスは試しましたか？前使った中でこれが結構よかったです。試してみてください

https://imgupscaler.com/

また、その後思い出したんですが、あのアニメーションも内蔵されている 2D Simple Character : Swordman のアセットを使うなら、キャラの体と脚とかを分ける必要があるかもしれないです。なのでまずそのアセットを入れてからやり方を模索した方がいいかもしれないですね。

**Comment by Onka10** [comment]
![HBJnZ4kt_4x](https://user-images.githubusercontent.com/87790609/147755895-97498bfe-01c5-47e2-b2f6-f77d7c03f600.png)
リンクのもの試しましたが変わらないですね、解像度上げるのはそんなに手間じゃないのでやってしまいます

アセットの件は了解しました。ただ、たしか足や頭の位置を今のデザインだとずらしてるはずなのでアニメーションは結局作り直すことになりそうな気がします

**Comment by Onka10** [comment]
ディスコードの進捗動画を見ていると、主人公はの移動とジャンプモーションは作成してしまっても大丈夫な気がしましたが作業を開始した方が良いですか？

**Comment by Onka10** [comment]
主人公の画質は修正したものを作成した方が良いのかについてお聞きしたいです

**Comment by JiaChen-Zeng** [comment]
モーションの作業はいいと思いますよ。アセットを導入することからですね。そちらでできそうですか？

主人公の画質の修正は実は今のゲーム画面を見ればそこまでぼやけてないので、優先度としては高くない気がしてきましたね。アップスケーリングした主人公の絵を 2048x2048px にして当面それを使えばよさそうです。

**Comment by Onka10** [comment]
分かりました。
ではアセットを導入してテストしてみます。
パスに指定はありますか？

**Comment by JiaChen-Zeng** [comment]
特にないです。まずデフォルトのパスで大丈夫と思います。あとでも変えられますから

**Comment by Onka10** [comment]
主人公をアセットの元の状態に戻していたのでアニメーションを作成する必要が無くなったので、このissueはcloseしても良いと思いましたがどうですか？

**Comment by JiaChen-Zeng** [comment]
そうですね。今必要なのは絵の向きをちょっと変えるだけですね。たぶん閉じて大丈夫です。向きを変えるタスクは #66 にあります。
