### ISSUE TITLE
画面のUXデザインを完成する

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#21]
# ライフポイント

わたしの意見ですが、「正」の文字自体を主人公のライフポイントに使わないほうがいいと思います。賢そうなデザインに見えますが、文字一つしかなく実際ダサく見えるかなと思います。代わりに、「正」の文字が書かれている盾を複数個使ってライフポイントを表すほうがいいかと思います。

# ステージ選択

下から上まで難しいステージになるような感じをイメージしています。絵は簡単でも大丈夫です。
<details>
  <summary>ステージ選択のイメージ図（クリックして展開）</summary>

  ![image](https://user-images.githubusercontent.com/3676278/147177982-55e69acd-73bf-4a2f-a65b-9f386d85949d.png)a5168ad82b77.png)
</details>

**Comment by Onka10** [comment]
!更新
現在想定している画面
1、タイトル画面：優先度中
2、クレジット画面：優先度高
3、チュートリアル画面：優先度中
4、ゲーム画面：優先度高
5、クリア画面：優先度中

**Comment by JiaChen-Zeng** [comment]
チュートリアルは画面を丸ごと使うんですか？簡単に作るならわたしはポップアップウィンドウみたいでいいんじゃないかなと思っています。

**Comment by Onka10** [comment]
簡単に説明できるならポップアップで可能ですが、仕様を読んだ感想としてはプレイヤーが覚えるべき事が多くチュートリアルを作成した方が良いかと思いました。

**Comment by JiaChen-Zeng** [comment]
なるほど。レベルデザインで覚えさせるのはどうですか？プログラミングがあまり必要ないのでコストパフォーマンスが結構よくて、そして効果は一番いいと考えてます。

Onka10さんの考えているチュートリアル画面は、インタラクティブ性のあるフェイクゲームのような感じでしょうか？

**Comment by Onka10** [comment]
チュートリアル専用にステージを作成するつもりでした。しかし、レベルデザインで一つずつ覚えさせるのが理想ですね
了解しました

**Comment by Onka10** [comment]
### 現在想定している画面

> 0、タイトル画面：優先度中
- ゲームスタート
- クレジット画面のポップアップ
- 音量の調整

> 1、クレジット画面：優先度高

- クレジットの表記(メンバーの名前、使用したアセット)
- クレジットポップアップの消去

> 2、ゲーム画面：優先度高

- ゲーム処理
- ライフポイント
- 音量の調整
- ステージマップ、これは今ステージどのどこに居るのかと周囲を把握するミニマップが望ましいです
- 現在の高さの表示
- ゲームスタートからの時間を表示

> 3、ゲーム終了画面：優先度中

- タイトル画面へ戻る処理
- リトライ処理
- 頂上まで登ったならクリアした事を表す処理、途中で死んでしまったら死んでしまった事を表す表示
- 登った高さの表示
- クリアタイムの表示

**Comment by Onka10** [comment]
![u1w_uiux](https://user-images.githubusercontent.com/87790609/147319974-9fb6baa1-a26f-4def-9f04-0d9bf96a622e.png)

**Comment by Onka10** [comment]
ゲーム画面の仮配置が出来ました。確認お願いします

**Comment by JiaChen-Zeng** [comment]
これで問題なさそうです！ざっとでいいので issue の進捗の数値もちょっと変えておいてくださいね。

今、どのステージにいるの情報も必要かもしれないなと思いました。でも恐らく HUD ではなく、次のステージに入るときにわかればいいので、ヒントを一個置けばよさそうです。

**Comment by Onka10** [comment]
issueの値というのが見当たらないのですが、もしかして先日説明していたタスク管理のページのことですか？

今どのステージにいるかは背景を変えることで表現が可能だと考えています。
これは仮に背景の絵を用意しない場合でも色で違いを表現することも可能だと思います。

ステージが切り替わった時にどうやってプレイヤーにステージの切り替わりを伝えるかは考えておきます

**Comment by Onka10** [comment]
画面遷移についてですが、Doodle Jumpのように一画面で完結させても良いかもしれませんね

**Comment by JiaChen-Zeng** [comment]
はい、わたしも背景とかでもわかると思います。でも儀式感というか、ストーリーが次の章に入ってきた実感も欲しいかなと感じました。あくまでも個人的な意見なので、これがいいとは限りません。参考くらいにしてください。

一画面だと、ステージ選択はどうなりますか？

進捗の記録はここです！わたし最初も見つからなかったです。GitHub の UX ちょっと改善する必要ありますよね。
![image](https://user-images.githubusercontent.com/3676278/147320818-73c66fc7-df9a-4966-bcb4-39068fbaa64c.png)

**Comment by Onka10** [comment]
そこは私は入力出来なくなっています。
おそらく権限が許可されてないのではないでしょうか？

**Comment by JiaChen-Zeng** [comment]
なるほど、GitHub Organization を使ってなかったので公開しても他の人は変えられないみたいですね。考えてなかったです。今招待を送ってみました。

**Comment by Onka10** [comment]
進捗入力できました。ありがとうございます。

ステージ選択ですが
プラン1、最初のステージにショートカット用の扉を作成する
プラン2、画面右上のオプションボタンからステージ選択を出来るようにする
プラン3、HADESのように毎回最初からやり直しで選択は出来ない
の3択だと思います

**Comment by JiaChen-Zeng** [comment]
1. 個人的に扉があるとゲーム世界が実世界の空間のように感じるので、心象世界と衝突してしまう気がします。たぶんこれは一番合わないなと思いました。
2. ポップアップウィンドウでステージ選択ですか？そうなるとステージ選択画面と近いですね。でもゲーム画面でステージ選択ができるゲームってあまり見たことがない気がします。少し変かなと思いました。やるなら独立した画面のほうがいいかもしれません。
3. わたし死んでて最後までプレイできないので個人的に好きじゃないです（笑）。HADESはローグライクでリプレイアビリティがあってそれができるので、今この企画はまだそこまでの深さとリプレイアビリティはないのでやり直すのは若干挫折感あるかなと思いました。

たぶんやはり単独の画面がいいかなーって今考えてます。でもあまり使われない可能性もある気がしなくもないです。どういうときにプレイヤーがステージ選択をすることを考える必要があるかもしれないです。

**Comment by Onka10** [comment]
分かりました。では新しいアイデアとして
タイトル画面からゲーム画面に移動前にステージ選択画面を新たに追加します。
最初はステージ1しか選択できませんが、一度新しいステージに到達すると最初に選択できるステージが増えるというのはどうですか？

**Comment by JiaChen-Zeng** [comment]
正直考えれば考えるほど前のステージに戻ることはめったにないので、ステージ選択機能なんていらないなと思えてきました🤔ゲームジャムのゲームとして前のステージに戻るほどプレイされない気がしましたね。そうなると余計なリソースが結構かかってしまうことになってしまいます。

ということでステージ選択はなくしましょうか。

**Comment by Onka10** [comment]
ステージ選択を無くすのは了解です。

一番実装が楽だと思われるHADES方式で良いですか？

**Comment by JiaChen-Zeng** [comment]
HADES の感じでいいと思います！正確にいうと今[セーブポイント](https://github.com/JiaChen-Zeng/PRNL-Alpha01/wiki/%E3%82%B3%E3%82%A2%E3%82%B2%E3%83%BC%E3%83%A0#セーブポイント)の仕様があるので、失敗するときはステージ1からやり直しじゃなくて、今いるステージのスタート地点からやり直しですね。

**Comment by Onka10** [comment]
了解です
ステージ選択が無いとするとタイトル画面も要らないように思えてきました。
前の企画のようにタイトル画面、クレジット画面、ゲーム画面、リザルト画面を同じにしてしまっても良いですか？
参考ゲームとしてDoodle Jumpを例に挙げられていましたが、今回のUI/UXもそれに似せることになりそうです

**Comment by JiaChen-Zeng** [comment]
なんか同じ流れになってきちゃったようとはいえ、今回はタイトル画面は必要だと思います！ゲームスタートを押してストーリーに入っていった感がほしいですね。初めからゲームの画面が見えてるのはストーリー性が弱くインタラクティブ性が高い比較的にカジュアルなゲームのイメージがあります。

タイトル画面に「CONTINUE」と「NEW GAME」があるのが見えました

**Comment by Onka10** [comment]
セーブデータがある状態でNEW GAMEを選ぶと今あるセーブデータは消えますか？

また、ゲームをクリアした時にもセーブデータは消えますか？

**Comment by JiaChen-Zeng** [comment]
確かに特別な処理を加えないとセーブデータは消えますね。そしてゲームをクリアした時はセーブデータは（クリア判定に使うロジック上の）ステージ 5 でしょうか。

**Comment by Onka10** [comment]
セーブがある状態でNEW GAMEを選択したときのUI案を考えてみました。確認ください
![caution](https://user-images.githubusercontent.com/87790609/147336408-84931926-a8aa-47c6-b5b9-ffdb95212bbc.png)

クリアした場合、クリア判定を残すのは了解しました。
UIについてのアイデアはありますか？

**Comment by JiaChen-Zeng** [comment]
このUI案でいいと思います！そういえばこういうポップアップウィンドウみたいに、他のところでも使われそうな共通のコンポーネントがあったら、共通の仕様としてまとめてくださいね。

> UIについてのアイデアはありますか？

クリア画面のUIのアイデアということですか？今はまだ考えてないです

**Comment by Onka10** [comment]
わかりました。
共通のUIに関してはwikiにまとめます。仮素材なので具体的には書けませんが、何が必要かは記入しておきます

クリア画面のUIのアイデアではなく、クリア後にタイトル画面のUIをどう変更するかです。
そもそもタイトル画面のUI案を共有してませんでしたね。

タイトル画面のUI案を見ながら、ゲームをクリアしてタイトルに戻った場合、continueボタンをどうするかを聞きたいです

**Comment by Onka10** [comment]
![titlescene](https://user-images.githubusercontent.com/87790609/147337839-3208e7be-e080-4a46-b1e7-8b2d8b50522a.png)

タイトル画面のUI案です

**Comment by Onka10** [comment]
クレジットポップアップ
![クレジット](https://user-images.githubusercontent.com/87790609/147338441-d37695df-c8a8-45b1-a627-92bccfa9c7cb.png)

**Comment by JiaChen-Zeng** [comment]
クリアしたらContinueしてももう他にやることないですよね。そしたら必要なくなる気はするんですが、なくしちゃうとセーブデータが消えたみたいになるのが難点かもしれないですね。とはいえ実際のゲームプレイに影響が大きいところでもなさそうなので、消してしまってもいいかなと思いました。

UI案はこれで十分かもしれないですね。ただContinueのほうがよく使われそうと思うので、一番目にしたほうがいいかなと。あとはあのファイルみたいなアイコンはクレジットですか？

**Comment by Onka10** [comment]
了解です。
ではクリア後のタイトルはNEW GAMEのみ表示とします。
しかし、データが消えてしまった感があるのは私も悲しいので、簡単に実装できる対策案を考えておきます

ファイルみたいなアイコンはクレジットです。
説明が足りていないのは承知しています。画面遷移と説明は後ほど足します。

歯車は設定ボタンです。最初の案では音量調節のみでしたが
多言語対応などもこのチームなら可能そうだと思いました。

**Comment by JiaChen-Zeng** [comment]
クレジットであってたんですね。まだ作ってるときは説明が若干足りなくてもそれで大丈夫です！

多言語対応についてはわたし実はゲーム日→英のゲームローカライズ職を目指してる方も知ってます。でも対応するとしても今回のゲームジャムではあまり評価は変わらないので、恐らくゲームジャムのあとですね。でもそのときになったらまだ続けられる人は少なめかもしれないです。

**Comment by Onka10** [comment]
ではメイン言語どうしますか？
unity roomはほとんどのゲームが日本語で作られてますし日本語にしますか？

**Comment by JiaChen-Zeng** [comment]
もちろん日本語です！

**Comment by Onka10** [comment]
音量設定画面です
![audio](https://user-images.githubusercontent.com/87790609/147347770-f64f9219-5192-43df-8ab1-ff2874217580.png)

**Comment by Onka10** [comment]
クリア画面、クリア時と途中で失敗した時の差
![おめでとう](https://user-images.githubusercontent.com/87790609/147348273-1709290a-ca73-4fff-8ca0-7a801ccca992.png)
![gameover](https://user-images.githubusercontent.com/87790609/147348276-8afb941b-edb2-4504-86f2-ebb013299a5f.png)
分

**Comment by Onka10** [comment]
現時点での想定している画面は以上です。
追加や修正があれば修正します。
画面遷移は少しおまちください

**Comment by JiaChen-Zeng** [comment]
音量設定画面はこれでいいと思います。そういえば音量設定の機能って必要でしたっけ？

クリア画面はステージクリアをイメージしてるでしょうか？今見てみたら仕様書の文章がおかしかったので申し訳ないですね。ゲームクリアは全ステージをクリアすることを指します。なのでこの画面は合わないかもしれません。今考えたんですが、ゲーム内で「ゲームクリア」っていう文字を表示してなんか花火とかエフェクトを付けてあげればいいかなと。

ゲームオーバー画面はだいたいこれでいいと思います！現在のステージ数の表示も一個ほしいです！

ちなみに今UIのテキストは全部英語のようですが、実装時に日本語に変える計画ですかね？

**Comment by Onka10** [comment]
ゲームクリアはその演出を採用するという事であればクリア画面は消しておきます

現在のステージ数については了解しました
UIテキストは使用言語が不明だったので英語だったり日本語が混ざってます。本素材作成の際に修正します

**Comment by Onka10** [comment]
日本語化と修
![クレジット日本語](https://user-images.githubusercontent.com/87790609/147352626-e677e259-4f1f-491a-b8e1-fb02e51474c0.png)
![音量設定日本語](https://user-images.githubusercontent.com/87790609/147352627-9f16d2b2-1df5-4673-aab6-0c5072503010.png)
![ゲーム画面日本語](https://user-images.githubusercontent.com/87790609/147352628-b04252ae-6930-4679-b3a4-873cbfaa6ef7.png)
正

**Comment by Onka10** [comment]
![gameover日本語](https://user-images.githubusercontent.com/87790609/147353834-d9d68085-2846-45fe-b704-2ecf39e9db07.png)
game over画面を日本語に修正

**Comment by Onka10** [comment]
### 画面構成修正版

> 0、タイトル画面：優先度中
- ゲームスタート
- クレジット画面のポップアップ
- 音量の調整のポップアップ

> 1、クレジット画面：優先度高

- クレジットの表記(メンバーの名前、使用したアセット)
- クレジットポップアップの消去

> 2、ゲーム画面：優先度高

- ゲーム処理
- ライフポイント
- 現在のステージ数
- 現在の高さの表示
- ゲームスタートからの時間を表示
- オプションボタン

> 3、ゲーム終了画面：優先度中

- タイトル画面へ戻るボタン
- リトライボタン
- 登った高さの表示
- クリアタイムの表示

**Comment by Onka10** [comment]
> 音量設定画面はこれでいいと思います。そういえば音量設定の機能って必要でしたっけ？
> 
> クリア画面はステージクリアをイメージしてるでしょうか？今見てみたら仕様書の文章がおかしかったので申し訳ないですね。ゲームクリアは全ステージをクリアすることを指します。なのでこの画面は合わないかもしれません。今考えたんですが、ゲーム内で「ゲームクリア」っていう文字を表示してなんか花火とかエフェクトを付けてあげればいいかなと。
> 
> ゲームオーバー画面はだいたいこれでいいと思います！現在のステージ数の表示も一個ほしいです！
> 
> ちなみに今UIのテキストは全部英語のようですが、実装時に日本語に変える計画ですかね？

音量設定は最初の画面構成案に入れていて、特に指摘が無かったので作ってしまいましたが、確かに要らない気もします。
消しますか？

**Comment by JiaChen-Zeng** [comment]
音量設定は消しましょうか。

ゲーム画面にいつも現在のステージ数を表示させるのは必要ないですね。新しいステージに入ったときにだけ表示させたいと考えました。

他はこの構成で大丈夫と思います！

**Comment by Onka10** [comment]
音量設定については了解です。

ステージの表記については
・今のステージは背景でプレイヤーに伝える
・ステージが変わった時はUIではなく演出で伝える
ですね

**Comment by JiaChen-Zeng** [comment]
それで合ってます！その演出も正確に言えばUIかなー

**Comment by Onka10** [comment]
![Screenshot 2021-12-24 at 14-45-18 画面のUXデザインを完成する · Issue #21 · JiaChen-Zeng PRNL-Alpha01](https://user-images.githubusercontent.com/87790609/147354634-7a465cfa-774a-4221-8b8f-7108e6eec6a1.png)

最終的な画面遷移です。

**Comment by Onka10** [comment]
> それで合ってます！その演出も正確に言えばUIかなー

ではクリア演出とステージクリア演出は私の担当になりそうですね。
wikiに追加しておきます

issueも新たに追加してもらえますか？

**Comment by Onka10** [comment]
最終的な画面遷移図です
![Screenshot 2021-12-24 at 22-02-09 Untitled Diagram drawio - diagrams net](https://user-images.githubusercontent.com/87790609/147354745-f74dcc4f-648c-4f19-ad7b-da4faad2532b.png)

**Comment by JiaChen-Zeng** [comment]
ゲーム画面からタイトル画面にも行けると思います！

そういえばゲーム画面のオプションボタンで出るウィンドウはまだ考えていないようです。

**Comment by Onka10** [comment]
そうでした。それについてお聞きしたいと考えていました。

ポーズ画面(ポップアップ)
・タイトルに戻る
・ゲームに戻る

これ以外に欲しい機能はありますか？

**Comment by JiaChen-Zeng** [comment]
これで十分と思います！

**Comment by Onka10** [comment]
画面遷移図の修正版です
![Screenshot 2021-12-24 at 22-31-45 Untitled Diagram drawio - diagrams net](https://user-images.githubusercontent.com/87790609/147356185-5b53832b-e133-4f81-8d80-805c2f7a0978.png)

**Comment by JiaChen-Zeng** [comment]
ポーズウィンドウからゲーム画面に戻れる以外問題ないと思います！

そういえばウィンドウと画面が一緒になってますね

**Comment by Onka10** [comment]
修正します

**Comment by Onka10** [comment]
![pause](https://user-images.githubusercontent.com/87790609/147356859-e9ff229b-d85c-4fb7-8426-7f5319bac6a4.png)

ポーズ画面仮デザインです

**Comment by Onka10** [comment]
画面遷移修正です
![Screenshot 2021-12-24 at 22-49-29 Untitled Diagram drawio - diagrams net](https://user-images.githubusercontent.com/87790609/147357093-b91678fe-b37b-45e1-b4cc-0b2261fdc8cd.png)

**Comment by Onka10** [comment]
### 画面構成修正版2

> 0、タイトル画面：優先度中
- ゲームスタート
- クレジット画面のポップアップ

> 1、クレジット画面：優先度高
- クレジットの表記(メンバーの名前、使用したアセット)
- クレジットポップアップの消去

> 2、ゲーム画面：優先度高
- ライフポイント
- 現在のステージ数(背景で表示)
- 現在の高さの表示
- ゲームスタートからの時間を表示
- ポーズボタン

> 3、ゲーム終了画面：優先度中
- タイトル画面へ戻るボタン
- リトライボタン
- 登った高さの表示
- クリアタイムの表示

> 4、ポーズ画面：優先度高
- タイトル画面へ戻るボタン
- リトライボタン

**Comment by Onka10** [comment]
ゲームオーバーの修正
![gameover_f](https://user-images.githubusercontent.com/87790609/147358551-43a00eba-a55b-45da-bd20-71291b9ecc78.png)

**Comment by JiaChen-Zeng** [comment]
これで UX デザインはそろそろ終わった気がします。次に何をしますか？あ、仕様書も書かなきゃいけなかったですよね。

あとはこの UI を Unity 内に置くことは難しくないと思うので、たぶんそれも一緒にやってもらえたらいいかなと。

**Comment by Onka10** [comment]
そうですね、とりあえず仕様書をまとめます。

わかりました。Unity用にUIを最適化しておきます

**Comment by Onka10** [comment]
![title](https://user-images.githubusercontent.com/87790609/147358822-e6e5266b-8c03-4d89-aabb-d880546bf926.png)

タイトル修正

**Comment by Onka10** [comment]
### #21最終タスク
Unity用にUIを変換する。それについての仕様を書く

**Comment by JiaChen-Zeng** [comment]
やることが若干違ってきたので、新しい issue を作った方がいいと思います！そして issue お互い一回メンションし合えばさらにいいですね

**Comment by Onka10** [comment]
ではこれはクローズします
