### ISSUE TITLE
戦略性が出るように「正」のパーツのパターンを考える

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#3]
> では正のパーツを考えたいです。既にパーツがどう動くかの仕様は固まっていますが、どんなパーツがよりプレイヤーを楽しませることが出来るのかについては議論がされていません

> 降ってくるパーツを考えるのを手伝って欲しいです。
正を組み立てるパズルゲームなので、組み立てる戦略性を産むようなパーツがあると助かります。難しいですがお願いします。
> コンセプト立案など私のタスクが終われば議論に私も参加するのでそれまでの間お願いできますか？

>コンセプト
>上から降ってくるパーツを土台を回転させながら上手く積み上げて正の字を作るアクションパズル

>目指す面白さ
>降ってくるパーツを土台のどの面に付けると効率的に文字が作れるのかを考えて実行するのが楽しい

**Comment by JiaChen-Zeng** [comment]
パーツの組み立てのゲーム性がパーツのデザインにかかっているようなのでかなり大事な部分です。今はほかのパターンがあるか考えることに取り組んでいます。ほかに開発できる部分もあるので、完成は明日夜まででもいいと思いました。

「正」の形だけ消せるんじゃなくて、「下」、「上」、「止」でも消せるようにできないかとわたしは考えました。しかし、「上」と「止」で消してしまったら、「正」はいつまでも完成することはないです。とはいえ、「正」を完成しなければならないというわけではなく、「正」の一部分を使ったパズルゲームとしてもお題はクリアできると思われます。
![image](https://user-images.githubusercontent.com/3676278/146800459-4ad165ba-f6c3-4802-bfa8-576b3bdeb209.png)

**Comment by JiaChen-Zeng** [comment]
@lyn-teambeta がパーツのほぼ全パターン(?)を列挙してくれました。
https://docs.google.com/presentation/d/1PuMF1H0Uk-lAaD4MHiefaQXf0pJx57bQlFJb4i2Vq5o/edit?usp=sharing

一体になっていないパターンは積みあがると空いて見えるところが出てしまうので、これらは良くないだろうと思いました。

**Comment by JiaChen-Zeng** [comment]
落ちてくるパーツが理論上高確率（80%~100%）で消せるように、パーツ配列を決定するアルゴリズムを考える必要がある。これがゲーム性を一番左右する、パーツデザインよりも大事なポイントとなります。

**Comment by Onka10** [comment]
開発中止
discontinue development
