### ISSUE TITLE
背景の絵を作る

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#51]
背景の色調で主人公、敵の色、弾の色などにかなり影響すると思うので、なるべく早いうちに作ったほうがいいです。背景はステージごと違うテーマのものが必要ですが、まずは 1 個で大丈夫だと思います。

**Comment by Onka10** [comment]
wikiに
カメラが上へ移動すると、背景はそれにつれて下へ移動する。背景は遠距離なので、移動する幅はカメラより小さい。ステージごとに背景の雰囲気が違う。
とありますが、つまり背景の絵は1ステージ分全てデザインするということですか？

**Comment by Onka10** [comment]
"背景の色調で主人公、敵の色、弾の色などにかなり影響すると思うので"
仰る通り、ゲームデザインと素材の用意のしやすさの面からmain cameraの子オブジェクトにした1080:1920の固定背景の方が良いかと思いますがどうでしょうか

**Comment by JiaChen-Zeng** [comment]
子オブジェクトにすると背景は動かないですね。そうなるとあまり動いてる感じがしないかもしれません。

恐らくこの部分のイメージ共有が足りなかったと思います。わたしは[継ぎ目がない完全にタイリングできるような背景画像](https://tips.clip-studio.com/ja-jp/articles/1302)をイメージしています。これだと素材の量は大きくならず移動している感もありますね。

<details>
  <summary>たぶんこういう感じになると思います（クリックして展開）</summary>

![背景](https://user-images.githubusercontent.com/3676278/147844142-910dc9a3-cf8a-4b50-ae18-e94eff4a1ecf.png)
</details>

そして次にステージ近いところになったら、ちょっとフィルターを付けるなり、小物を付けるなりしてスムーズに次のステージの背景画像に繋ぐようにすることになると思います。

**Comment by Onka10** [comment]
タイリングする画像については了解しました。
とりあえず、窓のあるタイリング可能な画像とステージのつなぎ目の画像を用意しようと思います。

用意する画像についてですが、まずはタイリングのテストが必要だと思うので、どれくらいのサイズの画像を用意すれば良いかお聞きしても良いですか？

**Comment by JiaChen-Zeng** [comment]
2048x2048で問題なさそうな気がします。全部埋まってるんじゃなくて透明なところもあるような画像になると思います。適当な画像一枚でまず実験してみたほうがいいですよね。実験のほうは簡単にできそうですか？

**Comment by Onka10** [comment]
`全部埋まってるんじゃなくて透明なところもあるような画像になると思います`
という部分が上手く理解できていないのですが、とりあえず2048×2048の大きさの画像に"多分こういう感じ"と提案頂いた画像を用意すればよろしいですか？仰る通り実験なので簡単なものを用意することは可能です

**Comment by JiaChen-Zeng** [comment]
一個簡単に作ってみます。

Markdown の引用の書き方はこんな感じですよ。`>` を使います

```
> 全部埋まってるんじゃなくて透明なところもあるような画像になると思います
```

**Comment by JiaChen-Zeng** [comment]
今実験用背景画像を入れました。`Assets/Textures/InGame/` にあります。あと実装関連の話は #52 のほうがいいかもと思ったのでコミットはあちらを参照しました。

**Comment by JiaChen-Zeng** [comment]
#35 の issue と重複してしまいましたね。これは /Close します。
