### ISSUE TITLE
背景を実装する

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#52]
背景はまず 1 個で大丈夫です。カメラと一緒に移動するのが必要です。

**Comment by JiaChen-Zeng** [comment]
タイル画像はここのパラメーターを使えるかもしれないです。

![image](https://user-images.githubusercontent.com/3676278/147855123-7956528a-6817-481e-b293-71b333ba012a.png)

**Comment by Onka10** [comment]
背景のテストを行い、コミットしました。
教えて頂いたTailedで問題ないと思います

**Comment by JiaChen-Zeng** [comment]
今ちょっと確認してみました。技術面で一番厄介なところはまだ解決されてないようですね。今のままでは 2048x2048px 透明なところがない画像しか使えないので、背景の絵のアスペクト比に制限がかかっている状態です。

わたしが思うには、透明な部分を除くと縦長のような背景画像になりそうなイメージを持っています。横長だと小さい区間で重複しているのが気になってしまうかもしれないですね。なので透明なところがある画像でも正確にタイル画像のように表示させる必要があると思います。でも制限があったとしても適切な絵は作れるというのならこれはやらなくてもいいですね。

または 2048x2048px にする必要はないという可能性もあるので、これについては改めて調べておきたいですね。そもそも自由に使えるなら何の問題もないです。

**Comment by Onka10** [comment]
恐らく技術で解決するよりも素材を作成する際に調節していく方が楽と思いますので、最適な画像サイズについての検証を開始します

**Comment by JiaChen-Zeng** [comment]
最適な画像サイズの検討ということは、2048は使わないということですか？たぶんそれでなんか問題出ることはないと思うのでそれでも大丈夫ですね

技術についてはまだ調べてないでしょ。厄介ですが難しい問題じゃないです。ちゃんと調べればわかります。

**Comment by JiaChen-Zeng** [comment]
ちなみに一つ注意すべき細かいところがありました。背景は近景と遠景から構成するようにしたいと考えています。近景はたぶんお持ちのイメージの通り室内の背景です。そして遠景は窓から見える外の景色（星空のような）です。

近景は静止のままで大丈夫です。遠景は近景より移動が遅く見えるように、カメラの移動に連れて同じ方向へと少し移動させる必要があります。

**Comment by Onka10** [comment]
今、2048*2048の透明の部分のない画像を用いて近景を実装してみました。
今回の実装を確認して頂いた上で
・画像が連続する違和感があるか
・それが時間を使って対応するほどの重大な問題であるか
についてお聞きしたいです。
違和感があるなら、議論していた技術で解決するか画像の比率を変更するかについて調べたいと思います
違和感があっても妥協できるなら、修正は後回しにして次のタスクを進めようと思います

遠景と近景の仕様については理解しました。
しかし、実装の優先度は低くしたいです。
理由としてはゲームに大きく関わるような要素ではないと考えているからです。

**Comment by JiaChen-Zeng** [comment]
確認してみました。おっしゃる通り言うほど違和感はありません。今のままで十分と思いましたね。これで一旦大丈夫だと思います。

遠景はカメラについてるみたいですね。これはこれで簡単にそれっぽくできてていい感じですね。遠景はその通り優先度が低いです。

だいたいこれでこの issue は一応完成にしても問題なさそうですね。残ってる細かいところは他に issue を作ろうかなと思います。→ #64

**Comment by JiaChen-Zeng** [comment]
@Onka10 前景の Pivot が間違ってたので、天地幅を変更するとき Y 座標も変えなければならないです。ここで Bottom に設定する必要があります。こちらでやっておきました。

![image](https://user-images.githubusercontent.com/3676278/148544749-7fb1d511-5875-49db-bdf9-6f149e9867de.png)
