### ISSUE TITLE
←と↑が同時に押下された場合、主人公がジャンプできない

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#58]
↖に向けるように盾の位置を制御しているとジャンプできなくなります。他の斜めの向きは大丈夫でした。この方向だけです。妙なバグかもしれないです。

**Comment by JiaChen-Zeng** [comment]
わたしのキーボードの<kbd>↑</kbd><kbd>←</kbd><kbd>Space</kbd>キーが衝突してる模様。もう一個キーボードは問題ありませんでした。他の人にも確認してもらいます。

**Comment by Onka10** [comment]
確認しました。特に問題は無かったです

**Comment by JiaChen-Zeng** [comment]
じゃあこれは問題ないですね
