### ISSUE TITLE
全仕様を洗い出して優先順位を決める

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#6]
これをやらないと開発に進めないので、一番大事です。洗い出してまず一番基本的な仕様を確定させて、そこから開発を進める必要があります。どういう仕様があるか、関係も含めて図を書いて洗い出した方がいい気がしますが、使わなくてもできるとは思います。使うなら、[Draw.io](https://draw.io/)を使ってください。GitHubと連携できるからです。

**Comment by JiaChen-Zeng** [comment]
> These are the following tasks need to be addressed
> 1. UI for the game. Need UI references or some kind of mockup.
> 2. From where will we get the UI assets or who will make them.
> 3. Scoring system
> 4. Win and lose criteria 
> 5. Gameplay mechanics - this should include all the scenarios which user can face.
> 6. Control schema 
> 7. Do you have any plans for Tutorials i.e First time user experience
> 8. Do we have more levels, if yes how will they differ from each other
> 9. What kind of visual effects will be there in the game and who is going to design and make the assets.
> 10. What will be the game name and logo.
> 11. Will we have leader board, if yes need to think of simple one. Like just saving the current user name and score locally.
> 
> これらは、対処する必要がある次のタスクです
> 1.ゲームのUI。 UI参照またはある種のモックアップが必要です。
> 2. UIアセ​​ットはどこから取得するのか、または誰が作成するのか。
> 3.スコアリングシステム
> 4.勝ち負けの基準
> 5.ゲームプレイの仕組み-これには、ユーザーが直面する可能性のあるすべてのシナリオが含まれている必要があります。
> 6.制御スキーマ
> 7.チュートリアル、つまり初めてのユーザーエクスペリエンスの計画はありますか
> 8.より多くのレベルがありますか？はいの場合、それらは互いにどのように異なりますか
> 9.ゲームにはどのような視覚効果があり、誰がアセットを設計および作成するのか。
> 10.ゲーム名とロゴはどうなりますか。
> 11.単純なものを考える必要がある場合は、リーダーボードを用意しますか。現在のユーザー名とスコアをローカルに保存するようなものです。

**Comment by Onka10** [comment]
今(2:00,pm,JST)
#6のタスクについて私が今考えていることを書きました。これから作業に入ります。作業によって完成されたものはGit hub にアップロードします。

1.私がUIのモックアップは作成中です。完成した場合は共有します。

2.UIのモックアップを参照しながら、ゲームデザイナーがそれらが作成出来るのか、取得出来るのかを議論します

3スコアシステム
現在ではパーツの仕様を検討中です。その結果によって細かい仕様は変更になります。
しかし、"正"の字が完成して特典が入るのは確定しています。

4.これは１人プレイ専用ゲームです。誰かと競う機能はありません。ゲームが終了する条件は"ゲームオーバーライン"と呼ばれる線をパーツが超えてしまうとゲームが終了します。
"ゲームオーバーライン"の詳細はUIについて書かれた仕様書を見てください。

5.構成されるゲーム画面の遷移図を作成します。これについてゲームデザイナーでの議論が必要になります。

6ゲームデザイナーによる議論が終了すると制御スキーマを作成します。

7.チュートリアルはチュートリアル専用のゲームシーンに記載する予定です。そのため、あなたはゲームシーンでチュートリアルを考慮する必要はありません。

8.私はこのゲームはレベルが一定であると考えています。それは最もスタンダードなテトリスのように、最初からずっとパーツが降ってくる条件に変更は無い事を意味します。

9.私達はチームメンバーの中から視覚効果の作成と設計が出来る人を探す必要があります。

10.私はゲーム名を考えています。ロゴはその次に考えます。私はこれらの要素はゲームにとても重要なことを理解していますが、私はその他の仕様を決める事の方が重要だと考えているのでこれらの要素は後で考えようと思っています。

11.実はunityroomの管理者が誰でも無料で使えるリーダーボードを作成してくれています。私は以前それを利用した事があります。しかし、このリーダーボードの問題は作成に必要な資料が日本語でしか書かれていないことです。
なので、私はこのゲームはスコアを表示するだけで良いと考えています。もし開発に余裕があるならばリーダーボードを私が実装します。
また、ツイッターとの連携もunityroomの管理者が作成しているので、私達が望むのならばそれもまた実装することができます。

**Comment by Onka10** [comment]
![u1w_titlescene](https://user-images.githubusercontent.com/87790609/146890583-1aa09f73-a873-45ab-9445-67ec041c61d0.png)

タスク1のタイトル画面UIの仮配置です

**Comment by Onka10** [comment]
開発中止
discontinue development
