### ISSUE TITLE
画面遷移と画面ごとの仕様

### ISSUE THREAD

**Issue by Onka10** [JiaChen-Zeng/PRNL-Alpha01#7]
https://docs.google.com/presentation/d/1QzC-G22vgYmJ6TBESRY0MmM0sfZAJ3ZiIc94t1C22Zc/edit?usp=sharing

このスライドを参考に画面ごとの仕様について、それが適切であるのかをゲームデザイナーで考えたいです
このスライドは誰でも編集が可能です

**Comment by JiaChen-Zeng** [comment]
ディスカッションでは今の案について概ね賛成でした。修正点はまず遊び方画面のボタンが必要なく、初回のプレイで遊び方のチュートリアルを表示すればいいという意見が出ました。そのほうがプログラミング上簡単だからだとのことです。

それにつれてタイトル画面、ひいてはスコア画面もなくすようなディスカッションになりました。しかし実質は画面の遷移アニメーションをデザインしたことになります。タイトル画面とスコア画面がなくなったというわけではありません。

今わたしは仕様をスライドからWikiに移して詳しくします。

**Comment by JiaChen-Zeng** [comment]
こんな感じのプレイ画面が提案されました。

![image](https://user-images.githubusercontent.com/3676278/146951072-ea55f2ed-88c1-440d-958d-1b158d36d44c.png)

気づいた問題点

1. パーツが積みあがったら、新しく落ちてくるパーツの全貌がよく見えなくなる。なのでプレイできる領域が減ってしまう。
2. 次のパーツを表示するUIがあると、そのUIとコアゲームのオブジェクトが四角なのに、斜めになっているUIが多く、統一感がないことがはっきりと出てしまう。

**Comment by JiaChen-Zeng** [comment]
https://design.penpot.app/#/workspace/6d8b88b0-60de-11ec-826f-e949c75b760d/e576ca40-6261-11ec-95ac-c2b142838c8b?page-id=e576ca41-6261-11ec-95ac-c2b142838c8b&layout=layers

いろいろ試してみたんですが、以上でいいと思いました。斜めはアニメーションも付けやすいので、これといって問題はなかったです。

問題点1はセルの大きさを小さくすることで解決できると @Onka10 さんが提案されました。わたしは以下のシステムデザインを経てセルの大きさを 95x95 px に、失敗判定ラインの半径を 615px に決めました。

```
平均プレイ時間を2分40秒とする
1回の操作約2秒
160秒 / 2秒 = 80回操作ができる
80%確率で消せると仮定
最終的に80*(100%-80%)=16個のパーツが消せず失敗
4方向あるので、1方向平均16/4=4個パーツが積みあがってる
以上より、セルの大きさはパーツを4個積めるようにしたい
小さいパーツがあることも考慮に入れて、正が3個くらいな大きさ
画面でオブジェクトを置いて大きさを微調整すると以下の数値が得られた
セルの大きさ=正の大きさ=95px
失敗判定ラインの半径=615px
```

チェックお願いします。これ終われば #12 に進められます。

**Comment by Onka10** [comment]
開発中止
discontinue development
