### ISSUE TITLE
スコアのUIを実装する

### ISSUE THREAD

**Issue by JiaChen-Zeng** [JiaChen-Zeng/PRNL-Alpha01#9]
まず必要と思われる API は以下です。適宜に追加してください。

```C#
int Score { get }; // スコア
void Add(int score); // スコアを上げる
void Reset(); // スコアを0にリセット
```

**Comment by lyn-teambeta** [comment]
using UnityEngine;
using UnityEngine.UI;

public class Score : MonoBehaviour
{
    // スコアを表示する
    public Text scoreText;

    // スコア
    private int score;

    // PlayerPrefsで保存するためのキー
    private string ScoreKey = "Score";

    void Start()
    {
        Initialize();
    }

    void Update()
    {
        // スコアを表示する
        scoreText.text = score.ToString();
    }

    // ゲーム開始前の状態に戻す
    private void Initialize()
    {
        // スコアを0に戻す
        score = 000;
    }

    // ポイントの追加
    public void AddPoint(int point)
    {
        score = score + point;
    }
}

**Comment by lyn-teambeta** [comment]
企画が変わる可能性もあるみたいですが、上げておきます

**Comment by Onka10** [comment]
開発中止
discontinue development
